import type { PerplexitySpace, SpaceInput } from './types'

export function serialize(spaces: PerplexitySpace[]): string {
  const exportData = {
    version: 1,
    exported_at: new Date().toISOString(),
    spaces_count: spaces.length,
    spaces: spaces.map(space => ({
      title: space.title,
      emoji: space.emoji,
      description: space.description,
      instructions: space.instructions
    }))
  }
  
  return JSON.stringify(exportData, null, 2)
}

export function parse(content: string): SpaceInput[] {
  try {
    const data = JSON.parse(content)
    console.log('Parsed JSON type:', typeof data, Array.isArray(data) ? 'Array' : 'Object')
    
    // Validate basic structure
    if (!data || typeof data !== 'object') {
      console.error('JSON is not an object')
      throw new Error('Invalid JSON format')
    }

    // Check for Perplexity history export format
    if (data.local && data.local.exportConfig) {
      console.error('Detected Perplexity history export instead of Spaces backup')
      throw new Error('This is a Perplexity History export, not a Spaces backup. Please select a file generated by this extension (perplexity-spaces-*.json).')
    }

    // Handle standard export format
    if (Array.isArray(data.spaces)) {
      console.log('Found standard spaces array with length:', data.spaces.length)
      return data.spaces.map((s: any) => ({
        title: s.title || 'Untitled Space',
        emoji: s.emoji || null,
        description: s.description || null,
        instructions: s.instructions || ''
      }))
    }
    
    // Handle root array format (legacy or manual)
    if (Array.isArray(data)) {
      console.log('Found root array with length:', data.length)
      return data.map((s: any) => ({
        title: s.title || 'Untitled Space',
        emoji: s.emoji || null,
        description: s.description || null,
        instructions: s.instructions || ''
      }))
    }

    console.warn('No spaces array found in JSON')
    return []
  } catch (err) {
    console.error('Failed to parse JSON backup:', err)
    return []
  }
}
